const SIGN_UP_DATA = {
  TITLE: "Create an account",
  LOGIN_LINK_PREV: "Already have an account? ",
  LOGIN_LINK: "Sign in",
  USERNAME: "User Name",
  USERNAME_PLACEHOLDER: "alpha2025",
  FIRST_NAME: "First Name",
  FIRST_NAME_PLACEHOLDER: "Your first name",
  LAST_NAME: "Last Name",
  LAST_NAME_PLACEHOLDER: "Your last name",
  EMAIL: "Email",
  EMAIL_PLACEHOLDER: "user@domain.com",
  PASSWORD: "Password",
  PASSWORD_PLACEHOLDER: "•••••••••••••••",
  CONFIRM_PASSWORD: "Confirm Password",
  CHECK_AGREE: "I agree to the ",
  TERMS_CONDITION: "Terms & Conditions",
  CREATE_BTN: "Create Account",
  ERR_LETTER_NUMBER: "Must contain only letters and numbers.",
  ERR_MIN_LETTER: "Must contain at least one letter.",
  ERR_MIN_DIGITS: "Must contain at least one number.",
  ERR_MIN_MAX: "Must be at least 8 characters long.",
  ERR_PASSWORD_MATH: "Password and Confirm must match.",
  EER_PASSWORD_CRITERIA: "password not match the requirements",
  ERR_AGREEMENT: "You must agree to the terms and conditions.",
} as const;
export default SIGN_UP_DATA;
